### ISSUE TITLE
Parse and output reaffirmed identifiers in short form

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-ieee#100]
@ronaldtse "ANSI C37.53.1-1989 (R1996) (Revision of ANSI C37.53.1-1982)" (https://ieeexplore.ieee.org/document/1389208)
I'm wondering what is (R1996) here. Looks like a revision and year, but it's not 1996 year... 
More PubIDs like that:
```
IEEE Std 1458-2005 (R2010)
IEEE Std 1541-2002 (R2008)
IEEE Std 665-1995 (R2001) (Revision of IEEE Std 665-1987)
IEEE Std 771-1998 (R2009)
```

Upd:
IEEE Std 771-1998 (R2009) https://standards.ieee.org/ieee/771/1006/
<img width="498" alt="image" src="https://user-images.githubusercontent.com/5849/159838104-34a4b8ed-91c8-4ea4-bbe0-f65671f44b0c.png">

So is it "reaffirmed"? Should we represent it the same way?

This should be in #17

_Originally posted by @mico in https://github.com/metanorma/pubid-ieee/issues/13#issuecomment-1077037147_

**Comment by ronaldtse** [comment]
@mico yes I think you are right, the "RYYYY" means "reaffirmed YYYY". We should keep the `(RYYYY)` pattern in the identifier. Thanks!

**Comment by mico** [comment]
duplicate #65
