### ISSUE TITLE
Parse "Unapproved" references

### ISSUE THREAD

**Issue by andrew2net** [metanorma/pubid-ieee#107]
We need to parse references like "IEEE Unapproved P802.21/D-14-2008-Sept". The Pubid should be equal to "IEEE P802.21/D14"
```ruby
> Pubid:Ieee::Identifier.parse("IEEE P802.21/D14") == Pubid:Ieee::Identifier.parse("IEEE Unapproved P802.21/D-14-2008-Sept")
=> true
```
Original https://github.com/metanorma/mn-samples-ieee/issues/5#issuecomment-1756770801

**Comment by mico** [comment]
Task update: we want to run tests against all Unapproved IDs in this dataset: https://github.com/relaton/relaton-data-ieee/blob/main/index-v1.yaml

**Comment by ronaldtse** [comment]
@mico yes this is the official dataset so we must support all identifiers.
