### ISSUE TITLE
Parse PubID with relationships (Amendments)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-ieee#14]
Some PubIDs refer to documents that amend another document. Amendments have a lowercase alphabet at the end of the unique identifier, starting with "a". e.g. "IEEE Std C95.1a-2010" means it is the 1st amendment to the previous edition of "IEEE Std C95.1".

```
ANSI C63.4a-2017 (Amendment to ANSI C63.4-2014)
IEEE Std C95.1a-2010 (Amendment to IEEE Std C95.1-2005)
IEEE Std C95.1b-2004 (Amendment to IEEE Std C95.1-1991 as amended by IEEE Std C95.1a-1998)
IEEE Std C57.18.10a-2008 (Amendment to IEEE Std C57.18.10-1998)
```

**Comment by mico** [comment]
```
IEEE P802.3az/D3.2, July 2010 (Draft Amendment of IEEE Std 802.3-2008)
IEEE P802.3bf/D2.0, July 2010 (Amendment of IEEE Std 802.3-2008)
```

@ronaldtse Should I treat "Draft Amendment" the same as "Amendment"?

**Comment by ronaldtse** [comment]
"Draft Amendment" is a draft of an Amendment, like how in ISO/IEC they have DAmd. So these two are different in publication status.

**Comment by mico** [comment]
Sometimes there are "Amendment to", sometimes "Amendment of".
E.g.:
```
ANSI PN42.38a/D1_May 2018 (Amendment to ANSI N42.38-2015)
IEEE P802.3bf/D2.0, July 2010 (Amendment of IEEE Std 802.3-2008)
```

@ronaldtse Is it ok if I'll represent both as "Amendment to"?

**Comment by ronaldtse** [comment]
> Is it ok if I'll represent both as "Amendment to"?

Agree. Let's use "Amendment to".

<img width="619" alt="Screenshot 2022-03-26 at 3 19 19 PM" src="https://user-images.githubusercontent.com/11865/160229366-312fdb46-f1cc-4da8-88d7-27015e8de6e2.png">

<img width="619" alt="Screenshot 2022-03-26 at 3 19 26 PM" src="https://user-images.githubusercontent.com/11865/160229374-7e8489b3-55b8-4a53-9285-045c7c0cedc0.png">
