### ISSUE TITLE
Parse PubID with relationships (Corrigendum)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-ieee#15]
Some PubIDs indicate a technical correction on a previous edition of the document. These are identified in the ID with `/Cor n-yyyy` where `n` is a serial number of the corrigendum, and `yyyy` the year of publishing of the corrigendum.

```
ANSI C63.5-2017/Cor 1-2019 (Corrigendum to ANSI C63.5-2017)
IEEE 1672-2006/Cor 1-2008 (Corrigendum to IEEE Std 1672-2006)
IEEE STD 1137-1991/Cor1-2009
```

**Comment by mico** [comment]
@ronaldtse corrigendum version is missing here, what we can do with that?
IEEE Std C57.12.10-2013 (Corrigendum to IEEE Std C57.12.10-2010)
IEEE Std C57.12.38-2016 (Corrigendum to IEEE Std C57.12.38-2014)
IEEE Std C57.19.03-2005 (Corrigendum to IEEE Std C57.19.03-1996)

**Comment by ronaldtse** [comment]
@mico it would be the first corrigendum, so Cor 1.

**Comment by ronaldtse** [comment]
@mico I just found this:
`IEEE Std C57.12.10-2013 (Corrigendum to IEEE Std C57.12.10-2010)`
https://ieeexplore.ieee.org/document/5685836/versions#versions

<img width="749" alt="Screenshot 2022-04-03 at 3 18 33 PM" src="https://user-images.githubusercontent.com/11865/161416319-84ddec40-aa07-4d1d-9dbb-dcc1614e675f.png">

It's hard to say which Cor number an item has based on the limited information given.
