### ISSUE TITLE
Parse PubID with relationship (Reaffirmation)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/pubid-ieee#17]
A "Reaffirmation" PubID indicates that this standard was published but re-confirmed to be valid at some point. This means the document has not been updated since its last edition, but provides the latest date when it was re-confirmed.

```
ANSI C50.32-1976 and IEEE Std 117-1974 (Reaffirmed 1984) (Revision of IEEE Std 117-1956)
ANSI N42.13-2004 (Reaffirmation of ANSI N42.13-1986)
IEEE Std 218-1956 (Reaffirmed 1980, 56 IRE 28.S2)
IEEE Std 202-1954 (Reaffirmed 1972)
IEEE Std 792-1995 (Reaffirmation of IEEE Std 792-1988)
```

**Comment by mico** [comment]
> IEEE Std 218-1956 (Reaffirmed 1980, 56 IRE 28.S2)

What is "56 IRE 28.S2" here? Is it another PubID, not related to reaffirmation, right?

**Comment by ronaldtse** [comment]
IRE is the institute of radio engineers, one of the predecessors of IEEE. 

We had IRE PubIDs parsed already, right?

**Comment by mico** [comment]
> IRE is the institute of radio engineers, one of the predecessors of IEEE.
> 
> We had IRE PubIDs parsed already, right?

My question: why another PubID together with reaffirmation. If we follow that logic then we can build something like:
IEEE Std 792-1995 (Reaffirmed 1988, 56 IRE 28.S2, Supersedes ASTM E380-1974, Amendment to IEEE Std 802.11-2012, etc...)

**Comment by ronaldtse** [comment]
> What is "56 IRE 28.S2" here? Is it another PubID, not related to reaffirmation, right?

I misunderstood what you meant. Yes, I think you are right, i.e:

* `IEEE Std 218-1956` is a dual PubID (the new PubID) for `56 IRE 28.S2`.
* `IEEE Std 218-1956` was reaffirmed in 1980.
