### ISSUE TITLE
Decide and implement numbers format for identifiers (dash vs dots)

### ISSUE THREAD

**Issue by mico** [metanorma/pubid-ieee#45]
I had an impression that most of IEEE identifiers have format: IEEE {number}.{part}-{year}
```
ANSI N42.35-2016
IEEE Std C37.20.1-2015
IEEE Std 1900.1-2019
IEEE Std P802.11a/D7
```

or IEEE {number}-{year}
`IEEE Std 515-2011`

As I can see now, it's now always like that:
```
IEEE Std 11073-10420-2020
IEEE P11073-10101a/D1, April 2015
IEC/IEEE P60076-57-129_D26
```

For IEEE document numbers starting with "P" when it's 4 digits after it's always using "." before next number
`IEEE P1666.1/D4, October 2015`
Only exception when it's year `IEEE P2410-2020/D5, December 2020`
For "P" and 5 digits, it's always using "-" exception only for a few identifiers:
```
IEEE P15288.1/D3.0, June 2014
IEEE P15288.1/D4.0, August 2014
IEEE P15288.1/D4.1, September 2014
IEEE P15288.2/D5.1, August 2014
IEEE P15288.2/D5.2, September 2014
```

I suspect most of the cases when number and part using "-" between it's coming from ISO format.

It's not complete research, I just pick random identifiers and investigate particularly numbers with "P" prefix.

_Originally posted by @mico in https://github.com/metanorma/pubid-ieee/pull/44#discussion_r835093748_

**Comment by ronaldtse** [comment]
I have a few points to add here:

1. I think we need to differentiate the numbering styles:

These:
```
ANSI N42.35-2016
IEEE Std C37.20.1-2015
```

Are "ANSI-style" codes. they go by "Lnn.nn-yyyy". We have seen some of them in the NIST publications too.

2. In IEEE, the pattern "nnnn.n" is used for "working groups" within committees.

For example:
* The standards committee "802" has internal working groups like "802.3".

A standard number can re-use the name of the working group.

For example:
* [IEEE 1666.1-2016](https://standards.ieee.org/ieee/1666.1/5812/) belongs to the P1666.1 working group
<img width="592" alt="Screenshot 2022-03-26 at 12 58 33 PM" src="https://user-images.githubusercontent.com/11865/160225387-d28bfb55-2c79-41d1-acfd-dfd72ed6ff1a.png">

Also, notice that this standard is not a Part standard: 
<img width="995" alt="Screenshot 2022-03-26 at 12 58 58 PM" src="https://user-images.githubusercontent.com/11865/160225397-1bdad668-b99a-464b-9476-71d98093bd8c.png">

3. It is unclear whether a "hyphen" or a "dot" indicates a part, and sometimes the PubID doesn't even indicate it is a part!

For example,
* [1003.2-1992](https://standards.ieee.org/ieee/1003.2/1408/) is a part: "IEEE Standard for Information Technology--Portable Operating System Interfaces (POSIX(R))--Part 2: Shell and Utilities"
* [IEEE 2745.2-2021](https://standards.ieee.org/ieee/2745.2/7261/) is a part: "IEEE Guide for Technology of Unified Power Flow Controller Using Modular Multilevel Converter–Part 2: Terminology"
* [62-1995](https://standards.ieee.org/ieee/62/210/) is a part: "IEEE Guide for Diagnostic Field Testing of Electric Power Apparatus - Part 1: Oil Filled Power Transformers, Regulators, and Reactors"
 * [IEEE/ISO/IEC P15026-2](https://standards.ieee.org/ieee/15026-2/10236) is a part: "ISO/IEC/IEEE Draft International Standard - Systems and software engineering--Systems and software assurance--Part 2: Assurance case"
* [PC62.42.5](https://standards.ieee.org/ieee/C62.42.5/10642/) is a part: "Guide for the Application of Surge-Protective Components in Surge Protective Devices and Equipment Ports - Part 5: 2-Terminal Electronic Current Limiters"

In the modelling and parsing, perhaps we should just identify what is a "standards identifier" without splitting parts. It is clear that we cannot know what is a part vs not a part just from the PubID.

In any case, the last `-yyyy` is definitely year, so at least we can extract that...

**Comment by mico** [comment]
> In the modelling and parsing, perhaps we should just identify what is a "standards identifier" without splitting parts. It is clear that we cannot know what is a part vs not a part just from the PubID.

You suggesting to parse numbers like "PC62.42.5" or "P15026-2" as a whole, without splitting them, exception only for years (`-yyyy`), right?

**Comment by ronaldtse** [comment]
Yes. What do you think?

**Comment by mico** [comment]
> Yes. What do you think?

Ok, let's see how it will work.

**Comment by mico** [comment]
@ronaldtse IEEE 15026-2-2011 (https://standards.ieee.org/ieee/15026-2/5234/) but
IEEE Std 1244-5.2000 (https://ieeexplore.ieee.org/document/882673)
Should we keep the same delimiter between year and number, or use "-" or "." for all identifiers with year?

**Comment by ronaldtse** [comment]
@mico Out of 6,187 entries (matching `-\d\d\d\d[\s\n\)]`), there are only 4 instances of `\.\d\d\d\d`:
```
IEEE Std 581.1978
ANSI/IEEE C37.30.1971
ANSI/IEEE Std C37.26.1972
IEEE Std 1244-5.2000
```

We should assume they are mistakes. Let's use `-`. Thanks!
