### ISSUE TITLE
Documentation required on creating identifiers

### ISSUE THREAD

**Issue by opoudjis** [metanorma/pubid-ieee#71]
@mico as the Metanorma maintainer, I need to be able to generate identifiers from metadata fields. I do not have an identifier that I can parse, as the current usecases have: I am generating the identifier from scratch.

The fields in https://github.com/metanorma/pubid-ieee/blob/main/lib/pubid/ieee/identifier.rb are not documented to the extent necessary for me to use them. This needs to be addressed as a matter of urgency. The same applies to https://github.com/metanorma/pubid-iso/issues/54 , which has been unactioned now for two months, and which has been holding up my work on ISO.

In particular, it is necessary for me to know:

* The legal values, for any enum values (e.g. for `type`)
* The range of values, when they are not obvious (e.g. what goes into `supersedes`)
* The meaning of attributes, when it is not obvious (what does `proposal` mean)
* How do generate particular kinds of identifier (e.g. identifiers with ™ vs ®; this may be an overlap with @andrew2net )

This is necessary for https://github.com/metanorma/metanorma-ieee/issues/112 to proceed, since I am not going to duplicate this code to generate the required identifier. From what I understand, it is also required by @andrew2net for his integration work.

**Comment by andrew2net** [comment]
@mico we need to implement the https://github.com/relaton/relaton-ieee/issues/21 functionality in this gem.
[Here](https://github.com/relaton/relaton-ieee/blob/a54c7cd55c544b2bef2e05d3f887481d909169fb/lib/relaton_ieee/pub_id.rb#L55) is my implementation.

**Comment by ronaldtse** [comment]
This is blocking https://github.com/ietf-tools/bibxml-service/issues/238#issuecomment-1201509668

**Comment by opoudjis** [comment]
Need to specify the required arguments for pubid-ieee class initialisation, and their expected effect.

**Comment by opoudjis** [comment]
So the initialisation parameters for the class, which inherits from Core, are:

* trademark: Boolean. Default false. If true, a trademark sign is inserted in the identifier. This can be either ™ or ®, depending on the number value, and the location of the trademark sign is after the number. Andrej has provided his existing implementation at https://github.com/relaton/relaton-ieee/blob/a54c7cd55c544b2bef2e05d3f887481d909169fb/lib/relaton_ieee/pub_id.rb#L55
* amendment: amendment number
* corrigendum: corrigendum number
* stage: DIS\d?|PSI|FCD|FDIS|CD\d?|Pub2|CDV|TS|SI
* approval: boolean, outputs Approved, Unapproved
* draft: draft number
* redline: true or false. Is a particular classification of documents, orthogonal to normal document classes
* month: month number, two digits

Inherited arguments used:
* edition
* publisher
* number
* part
* year

Test code at https://github.com/relaton/relaton-ieee/blob/e7a85f38953152fc38f4e9890ea533068c5b6f17/lib/relaton_ieee/rawbib_id_parser.rb

**Comment by ronaldtse** [comment]
This ticket is rather unclear on what needs to be done.

e.g. The trademark rendering is a rendering option, not a creation option.

**Comment by opoudjis** [comment]
What is the status on this? Yes, trademarking is indeed a rendering option.
