### ISSUE TITLE
Upgrade gem to use latest pubid-core

### ISSUE THREAD

**Issue by opoudjis** [metanorma/pubid-ieee#87]
This gem has:

````
  spec.add_dependency "pubid-iso", "~> 0.4.1"
````

but relaton-iso depends on pubid-iso 0.5.0.

I am consuming all the relaton gems at once in Metanorma; it is essential that all the latest pubid, relaton, and metanorma gems appeal to the same versions of the pubid gems. 

However, I cannot upgrade pubid-iso to 0.5.0 for this gem, because

````
An error occurred while loading spec_helper.
Failure/Error:
    class Identifier < Pubid::Core::Identifier
      attr_accessor :number, :publisher, :copublisher, :stage, :part, :subpart,
                    :edition, :draft, :redline, :year, :month, :type, :alternative,
                    :draft_status, :revision, :adoption_year, :amendment, :supersedes,
                    :corrigendum, :corrigendum_comment, :reaffirmed, :incorporates,
                    :supplement, :proposal, :iso_identifier, :iso_amendment
  
      def initialize(publisher: "IEEE", number: nil, stage: nil, subpart: nil, edition: nil,
                     draft: nil, redline: nil, month: nil, revision: nil,
                     iso_identifier: nil, type: :std, alternative: nil, draft_status: nil, adoption_year: nil,

TypeError:
  superclass must be an instance of Class (given an instance of Module)
# ./lib/pubid/ieee/identifier.rb:7:in `<module:Ieee>'
````

Please update to the latest pubid-core throughout the pubid stack. If you do not, Metanorma will downgrade to the lowest compatible version of all pubid; that in turn will downgrade relaton to the lowest compatible version, and that will throw out a lot of essential updates to relaton.

**Comment by opoudjis** [comment]
This is a prerequisite to releasing pubid-ieee. https://github.com/metanorma/pubid-ieee/pull/86 also is needed, to make rspec work.

**Comment by ronaldtse** [comment]
@mico can you please help fix this ASAP? Thanks.
